// LOGIN
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE"

export const LOGOUT_USER = "LOGOUT_USER"

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE"

export const POST_ID_REQUEST = "POST_ID_REQUEST"
export const POST_ID_SUCCESS = "POST_ID_SUCCESS"
export const POST_ID_FAILURE = "POST_ID_FAILURE"

export const CREATE_CLAIM_REQUEST = "CREATE_CLAIM_REQUEST"
export const CREATE_CLAIM_SUCCESS = "CREATE_CLAIM_SUCCESS"
export const CREATE_CLAIM_FAILURE = "CREATE_CLAIM_FAILURE"